_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 635ab38f-9dc1-4476-b72e-daeedbc5066f
name: 'Taylor Wills'
mail: t@ylorwills.com
slogan: ''
page:
  403: /node/6
  404: /node/7
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
